load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "SettingsUI",
    module_name = "SettingsUI",
    srcs = glob([
        "Sources/**/*.swift",
    ]),
    copts = [
        "-warnings-as-errors",
    ],
    deps = [
        "//submodules/Display:Display",
        "//submodules/AsyncDisplayKit:AsyncDisplayKit",
        "//submodules/TelegramCore:TelegramCore",
        "//submodules/AccountContext:AccountContext",
        "//submodules/TelegramPresentationData:TelegramPresentationData",
        "//submodules/TelegramUIPreferences:TelegramUIPreferences",
        "//submodules/ItemListUI:ItemListUI",
        "//submodules/PresentationDataUtils:PresentationDataUtils",
        "//submodules/PasswordSetupUI:PasswordSetupUI",
        "//submodules/SSignalKit/SwiftSignalKit:SwiftSignalKit",
        "//submodules/AppBundle:AppBundle",
        "//submodules/TelegramStringFormatting:TelegramStringFormatting",
        "//submodules/TextFormat:TextFormat",
        "//submodules/SearchUI:SearchUI",
        "//submodules/SearchBarNode:SearchBarNode",
        "//submodules/StatisticsUI:StatisticsUI",
        "//submodules/UrlHandling:UrlHandling",
        "//submodules/ShareController:ShareController",
        "//submodules/PhoneNumberFormat:PhoneNumberFormat",
        "//submodules/LocalizedPeerData:LocalizedPeerData",
        "//submodules/MergeLists:MergeLists",
        "//submodules/TelegramUI/Utils/GIF:GIF",
    ],
    visibility = [
        "//visibility:public",
    ],
)
